### ISSUE TITLE
Error message after login

### ISSUE THREAD

**Issue by ghost** [UbuntuDDE/bugs#49]
**Describe the bug**
I have an error message on each boot after login to my session

**Screenshots**
![Screen Capture_20201118211630](https://user-images.githubusercontent.com/74487465/99586228-b5d8ca80-29e7-11eb-99d8-4cf1f42f819c.png)

**Desktop (please complete the following information):**
 - Version 20.010

**Additional context**
I don't know where i can found a log file to know whats wrong here.
If you want more information, please telle me where i can grab them.

**Comment by serial02** [comment]
> **Desktop (please complete the following information):**
> 
> * Version 20.010
> 
> **Additional context**
> I don't know where i can found a log file to know whats wrong here.
> If you want more information, please telle me where i can grab them.


Hello

The message appears on every boot of Ubuntu-DDE 20.10 
Here are details of my configuration:

```
OS: Ubuntu 20.10 x86_64  
Kernel: 5.8.0-29-generic 
Uptime: 3 hours, 36 mins 
Packages: 2231 (dpkg) 
Shell: bash 5.0.17 
Resolution: 1920x1080 
DE: Deepin 20.10 
WM: KWin 
Icons: bloom [GTK2/3] 
Terminal: deepin-terminal 
CPU: Intel i3 540 (4) @ 3.067GHz 
GPU: Intel Core Processor 
Memory: 3403MiB / 7694MiB
```

I believe that in these below and already sent logs you will be able to see some relation with this error message and error, because when clicking on send message, it does not send any information to the official website of ubuntu and Github Ubuntu / bugs

https://github.com/UbuntuDDE/bugs/issues/60
https://github.com/UbuntuDDE/bugs/issues/54
https://github.com/UbuntuDDE/bugs/issues/53
https://github.com/UbuntuDDE/bugs/issues/52
https://github.com/UbuntuDDE/bugs/issues/48
https://github.com/UbuntuDDE/bugs/issues/47
https://github.com/UbuntuDDE/bugs/issues/44

@openarun

**Comment by openarun** [comment]
I am closing this bug because groovy is EOL and I believe the latest release of UbuntuDDE has this issue fixed. If you find this bug in the latest releases, please feel free to re-open and mention your UbuntuDDE Remix version.
