### ISSUE TITLE
Clock format reverts back after system reboot

### ISSUE THREAD

**Issue by haresh6x** [UbuntuDDE/bugs#6]
The clock format (24hour/12hour) revert backs however we change it from settings after the system reboot. Had to change it on every reboot.

**Comment by anantamishra** [comment]
Hey @haresh6x , Thank you for raising the issue here, This issue have been solved in the point release of UbuntuDDE i.e: UbuntuDDE 20.04.1 Release, Please do update the system and let us know that the issue is sloved or not?

Note: If you are on beta version of UbuntuDDE release then do reinstall the OS from the link below:
https://ubuntudde.com/download/
