### ISSUE TITLE
Dock changes the screen randomly

### ISSUE THREAD

**Issue by scroom** [UbuntuDDE/bugs#81]
**Describe the bug**
Since yesterdays updates the dock changes the screen randomly (or I have not yet recognized the regularity behind it).

**Expected behavior**
Dock should stay on the configured screen.

**Desktop (please complete the following information):**
 - Version 20.10

**Comment by samratsuzil** [comment]
Its a feature rather than bug. The dock doesn't switch randomly. Actually what happens is: if you move the mouse  to the location where there should be the dock and keep it there for 3 sec, dock appears there. Its helpful when you need the dock in that screen and it also makes your work more efficient in most cases.

Try it... It will make sense after you know how to use it...

**Comment by scroom** [comment]
Ok, you are right. Is it possible to deactivate this. Unfortunately not all windows respond to dock switching and then content is behind the dock and some programs can't be fully operated. Should I open a new bug report about this?

**Comment by rindia** [comment]
@samratsuzil  make sense 

Thanks

**Comment by scroom** [comment]
closing this and opening a new bug report for the missing setting option.

**Comment by suoko** [comment]
Crazy option, It changes screen but also position. I usually keep it in the left side of the left screen and it regularly switch to bottom of the central screen
